name: Lint PR

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  title-format:
    runs-on: [self-hosted, linux, x64, python-3.10]
    steps:
      - uses: amannn/action-semantic-pull-request@v3.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          validateSingleCommit: true
