name: Release

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: [self-hosted, linux, x64, python-3.10]
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3
        id: release
        with:
          release-type: simple
          token: ${{ secrets.GITHUB_TOKEN }}

