name: Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main, dev]

jobs:
  lint-workflow:
    runs-on: [self-hosted, Linux, python-3.10]
    steps:
    - uses: actions/checkout@v3
    - name: snakefmt
      run: |
        /usr/bin/poetry/bin/poetry install --with dev
        /usr/bin/poetry/bin/poetry run snakefmt workflow/Snakefile
        /usr/bin/poetry/bin/poetry run snakefmt workflow/rules/
        /usr/bin/poetry/bin/poetry run snakefmt workflow/scripts/

  run-workflow:
    runs-on: [self-hosted, Linux, python-3.10]
    needs: lint-workflow
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Test workflow
      run: |
        /usr/bin/poetry/bin/poetry install --with dev
        /usr/bin/poetry/bin/poetry run pytest