name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main, dev]

jobs:
  run-workflow:
    runs-on: [self-hosted, Linux, python-3.10]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Test workflow
      run: |
        source "/usr/bin/conda/etc/profile.d/conda.sh"
        conda activate
        mamba create -c conda-forge -c bioconda -c nodefaults --name test snakemake snakedeploy python==3.10.8
        mamba activate test
        conda config --set channel_priority strict
        snakemake --cores all --use-conda --directory .test || (for f in .test/logs/*; do echo $f; cat $f; done; for f in .test/logs/*/*; do echo $f; cat $f; done; exit 1)